version: '3.8'

services:
  nginx:
    ports:
      - "8080:80"  # 本番用に80ポートで公開
    restart: always  # サービスの自動再起動
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - remix_app

  remix_app:
    environment:
      - NODE_ENV=production
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
    volumes:
      - "${HOST_NAS_PATH}:${NAS_PATH}"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
      interval: 30s
      retries: 3

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    environment:
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
    networks:
      - webnet
    restart: unless-stopped
    depends_on:
          - nginx
